### ISSUE TITLE
BIOS Update / IPMI Update should be combined

### ISSUE THREAD

**Issue by galthaus** [digitalrebar/digitalrebar#116]
The update system should be merged into a single component update system.

The current form is fine, but it should function for more components.  A wider set of attributes should be included as well.  Or really be free form in the handling system.

This will allow for updating all parts of the dell systems.

**Comment by galthaus** [comment]
After playing with this some, I'm not sure this should be merged.  It is a little tricky with tool chains and other things.  I think it could be done, but is a large rework scheme.

A true merge and replacement would be something like:
A list of updates that contain a quad of:
  * a tool/script to get the current version of item present
  * a version that this update provides
  * an attribute to test against to get the wanted version
  * a tool/script to update the component.
  * optional: instructions/links to get the updates for this component

The update script would need to pull images from the provisioner.  Tools needed for the version and update scripts would need to be installed by a preceding role without a direct dependency.   Like raid and bios tools would need to be installed before this could run.   Also, sequencing issues between ipmi-discover, ipmi-flash, ipmi-configure, bios-*, and raid-* would have to be rethought because of the  combined flash-all role.  Doable, but more thought is needed.

**Comment by zehicle** [comment]
these items were converged.
