### ISSUE TITLE
Allow copying of Provisioner Boot Environments

### ISSUE THREAD

**Issue by wdennis** [digitalrebar/digitalrebar#194]
I have a use case where I need the same OS version installed, but with differing kickstart files, or other boot parameters. It would be handy to be able to copy an existing boot env, giving it a new name when copying, and then modifying it as needed, rather than creating a new one from scratch.

Cobbler, for instance, has a "Copy" button on the Profiles screen, which allows one to easily dupe an existing Profile, and save it under a new name...

![cobbler_profile_copy](https://cloud.githubusercontent.com/assets/5913397/22534242/c097f566-e8c0-11e6-90cb-424d81b06096.png)

(Of course if there is a better way to take a given Boot Environment and make such changes without copying, then that might be sufficient too, but I'm not sure that's possible.)

**Comment by zehicle** [comment]
This was implemented in Digital Rebar Provision.
