### ISSUE TITLE
Issue running run-in-system.sh

### ISSUE THREAD

**Issue by aledbf** [digitalrebar/digitalrebar#73]
I'm trying to install the admin node with:
`./run-in-system.sh --deploy-admin=local --access=local --admin-ip=$IPA`

after 50 minutes still waiting in `TASK [FORWARDER wait until Digital Rebar service is up [1 upto 40 minutes]]`

Inspecting the docker logs I see this in `compose_forwarder_1`:

```
Reading services
    2016/10/21 18:35:33 [WARN] agent: Check 'service:trust-me-service' is now critical
```

Any idea?
Thanks

**Comment by galthaus** [comment]
Hi @aledbf, 

For this case, the log to usually look at is in compose_rebar_api_1.  

I noticed that you ran the command with --access=local.  I think that should be --access=HOST most likely.  Try that first.

Thanks,
Greg

**Comment by aledbf** [comment]
@galthaus right. That was the issue.
Just in case the [docs](http://digital-rebar.readthedocs.io/en/latest/deployment/install/linux.html) use `local`

**Comment by aledbf** [comment]
@galthaus next issue: I cannot login.
(eula link empty, login button is never enabled)
![captura de pantalla 2016-10-21 a las 5 32 09 p m](https://cloud.githubusercontent.com/assets/161571/19610806/b6ca8286-97b4-11e6-8d43-b6e7909026a1.png)

**Comment by aledbf** [comment]
(eula is null, removing the validation !eula fixed the issue)

**Comment by galthaus** [comment]
Nice work.  We'll still need to look at the eula issue.

**Comment by zehicle** [comment]
EULA was resolved.  Also, fixed the port issue that was causing the timeout.
